version: 2.0.3.{build}
skip_tags: true
skip_branch_with_pr: false

clone_folder: C:\Centrifuge
image: Visual Studio 2019
platform: Any CPU

configuration: Debug

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

matrix:
  fast_finish: true

build:
  parallel: true
  project: Centrifuge.sln
  verbosity: minimal

branches:
  only:
  - develop

before_build: 
- cmd: "nuget restore"

after_build:
- ps: >
    mkdir CentrifugeDevelop\Centrifuge;
    mkdir CentrifugeDevelop\Managed;
    cp C:\Centrifuge\Centrifuge\bin\$env:CONFIGURATION\net35\Centrifuge.dll CentrifugeDevelop\Managed\;
    cp C:\Centrifuge\Centrifuge.UnityInterop\bin\$env:CONFIGURATION\net35\Centrifuge.UnityInterop.dll CentrifugeDevelop\Managed\;
    cp C:\Centrifuge\Spindle\bin\$env:CONFIGURATION\net35\Spindle.exe CentrifugeDevelop\Managed\;
    cp C:\Centrifuge\Spindle\bin\$env:CONFIGURATION\net35\Mono.Cecil.dll CentrifugeDevelop\Managed\;
    cp C:\Centrifuge\Spindle\bin\$env:CONFIGURATION\net35\install_windows.bat CentrifugeDevelop\Managed\;
    cp C:\Centrifuge\Spindle\bin\$env:CONFIGURATION\net35\install_linux.sh CentrifugeDevelop\Managed\;
    cp C:\Centrifuge\Reactor\bin\$env:CONFIGURATION\net35\LitJSON.dll CentrifugeDevelop\Managed\;
    cp C:\Centrifuge\Reactor\bin\$env:CONFIGURATION\net35\0Harmony.dll CentrifugeDevelop\Managed\;
    cp C:\Centrifuge\Reactor\bin\$env:CONFIGURATION\net35\Reactor.dll CentrifugeDevelop\Centrifuge\;
    cp C:\Centrifuge\Reactor.API\bin\$env:CONFIGURATION\net35\Reactor.API.dll CentrifugeDevelop\Centrifuge\;

artifacts:
- path: CentrifugeDevelop
  name: Centrifuge Bleeding Edge